site_name: AI Information
site_url: https://delpropo.github.io/obsidian/work/AI
repo_url: https://github.com/delpropo/obsidian/work/AI
repo_name: delpropo/obsidian

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration:
    - Bashrc Setup: bashrc.md
    - File Locations: file_location_yaml_prompt.md
  - AI Resources:
    - LLM Information: llm_info.md
    - Considerations: Considerations.md
  - Development:
    - Mercury Shell Scripting: mercury_shell_scripting.md
  - Planning:
    - Transition Plan: transition_plan.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  # Remove any other plugins that aren't installed
